#配置端口号
server:
  port: 8092

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_fyk?characterEncoding=utf-8
    username: root
    password: root

#mybatis配置
mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:conf/mybatis-config.xml