#配置端口号
server:
  port: 8092
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true


# 项目配置
project:
  captcha-open: false #是否开启验证码
  shiro:
    remember-me-timeout: 7 #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800 #Session会话超时时间，默认30分钟（秒）
  fileupload:
    file-path: E:/upload/ #文件上传路径

#netty 服务配置
netty:
  server:
    port: 9090
    host-name: localhost

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/project_fyk?characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    database: 0 #Redis数据库索引(默认为0)
    host: 192.168.1.110 #Redis服务器地址
    port: 6379 #连接端口
    password: #连接密码(默认为空)
    jedis:
      pool:
        max-active: 200 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间(负值标识没有限制)
        max-idle: 10 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
    timeout: 1000 #超时时间(ms)
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

#模板引擎
#mybatis配置
mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:conf/mybatis-config.xml

#云盘配置
file-manager:
  command: com.javaweb.MichaelKai.elfinder.command
  thumbnail:
    width: 80
  volumes[0]:
    Node:
    source: fileSystem
    alias: file
    path: E:/upload/cloudDisk
    defaultNode: true
    locale:
    constraint:
      locked: false
      readable: true
      writable: true
